"""add class_type and registration_status

Revision ID: 04be8ef97157
Revises: c28b9a4850ca
Create Date: 2026-03-30 17:19:55.856239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04be8ef97157'
down_revision: Union[str, Sequence[str], None] = 'c28b9a4850ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('class_type', sa.String(length=50), nullable=True))
    op.add_column('classes', sa.Column('registration_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'registration_status')
    op.drop_column('classes', 'class_type')
    # ### end Alembic commands ###
