"""update tuition fees

Revision ID: 05efe3ad2677
Revises: 708dca54f222
Create Date: 2026-04-22 10:04:38.060988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05efe3ad2677'
down_revision: Union[str, Sequence[str], None] = '708dca54f222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_fees', sa.Column('term', sa.Integer(), nullable=True))
    op.alter_column('tuition_fees', 'training_program_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuition_fees', 'training_program_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tuition_fees', 'term')
    # ### end Alembic commands ###
