"""add subject_id into classes table

Revision ID: 1333609b7436
Revises: 04be8ef97157
Create Date: 2026-03-31 13:49:17.542816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1333609b7436'
down_revision: Union[str, Sequence[str], None] = '04be8ef97157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'classes', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'subject_id')
    # ### end Alembic commands ###
