"""add status to subject table and teaching schedule table

Revision ID: 1b25a9a463f9
Revises: 7e6da5980161
Create Date: 2025-07-31 23:32:46.828687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b25a9a463f9'
down_revision: Union[str, Sequence[str], None] = '7e6da5980161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('teaching_schedules', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_schedules', 'status')
    op.drop_column('subjects', 'status')
    # ### end Alembic commands ###
