"""add missing foreign key

Revision ID: 247757407185
Revises: bfc6dd7f8f85
Create Date: 2026-02-25 20:19:11.286389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247757407185'
down_revision: Union[str, Sequence[str], None] = 'bfc6dd7f8f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'classes', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'examination_schedules', 'teachers', ['invigilator_2_id'], ['id'])
    op.create_foreign_key(None, 'examination_schedules', 'teachers', ['invigilator_1_id'], ['id'])
    op.create_foreign_key(None, 'scores', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'teaching_schedules', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'tuition_fees', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tuition_fees', type_='foreignkey')
    op.drop_constraint(None, 'teaching_schedules', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'examination_schedules', type_='foreignkey')
    op.drop_constraint(None, 'examination_schedules', type_='foreignkey')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    # ### end Alembic commands ###
