"""add createdAt and updatedAt userInformation table

Revision ID: 4952a37bd88c
Revises: be8dd00bed85
Create Date: 2025-07-20 14:13:23.688426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4952a37bd88c'
down_revision: Union[str, Sequence[str], None] = 'be8dd00bed85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_informations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_informations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_informations', 'updated_at')
    op.drop_column('user_informations', 'created_at')
    # ### end Alembic commands ###
