"""set gender to nullable

Revision ID: 4f20cb42d171
Revises: 92ef87aaedd0
Create Date: 2026-04-04 16:35:21.013026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f20cb42d171'
down_revision: Union[str, Sequence[str], None] = '92ef87aaedd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('teachers', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
