"""update student and student_class

Revision ID: 50f1b1d7b91d
Revises: c2594547d346
Create Date: 2026-03-21 14:32:11.912689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f1b1d7b91d'
down_revision: Union[str, Sequence[str], None] = 'c2594547d346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class', sa.Column('class_type', sa.String(length=50), nullable=True))
    op.drop_column('students', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('student_class', 'class_type')
    # ### end Alembic commands ###
