"""add field seats to room table

Revision ID: 5ab631f015b9
Revises: 9b261a17de7f
Create Date: 2026-03-23 20:05:56.273007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab631f015b9'
down_revision: Union[str, Sequence[str], None] = '9b261a17de7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'seats')
    # ### end Alembic commands ###
