"""update score table

Revision ID: 5b5ebd630176
Revises: 767830cc0eb5
Create Date: 2025-08-02 23:40:34.060434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5ebd630176'
down_revision: Union[str, Sequence[str], None] = '767830cc0eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
