"""update tuition fees table

Revision ID: 708dca54f222
Revises: 9a8e8a76781a
Create Date: 2026-04-18 16:45:26.136503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708dca54f222'
down_revision: Union[str, Sequence[str], None] = '9a8e8a76781a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_fees', sa.Column('price_per_credit', sa.Float(), nullable=False))
    op.add_column('tuition_fees', sa.Column('training_program_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tuition_fees', 'training_program', ['training_program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tuition_fees', type_='foreignkey')
    op.drop_column('tuition_fees', 'training_program_id')
    op.drop_column('tuition_fees', 'price_per_credit')
    # ### end Alembic commands ###
