"""add training program tables

Revision ID: 7564070f97b2
Revises: 5ab631f015b9
Create Date: 2026-03-29 17:38:25.844250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7564070f97b2'
down_revision: Union[str, Sequence[str], None] = '5ab631f015b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_program',
    sa.Column('program_type', sa.String(length=50), nullable=False),
    sa.Column('training_program_name', sa.String(length=100), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('specialization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_program_subject',
    sa.Column('training_program_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('rooms', 'seats',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'seats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('training_program_subject')
    op.drop_table('training_program')
    # ### end Alembic commands ###
