"""update score and score component

Revision ID: 767830cc0eb5
Revises: 800f6cacf46e
Create Date: 2025-08-02 23:25:03.383235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767830cc0eb5'
down_revision: Union[str, Sequence[str], None] = '800f6cacf46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_components', sa.Column('component_type', sa.String(length=50), nullable=False))
    op.drop_column('score_components', 'component_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_components', sa.Column('component_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('score_components', 'component_type')
    # ### end Alembic commands ###
