"""add password to students and teacher

Revision ID: 7e6da5980161
Revises: 4952a37bd88c
Create Date: 2025-07-22 21:17:50.328515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e6da5980161'
down_revision: Union[str, Sequence[str], None] = '4952a37bd88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password', sa.String(length=100), nullable=False))
    op.add_column('teachers', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'password')
    op.drop_column('students', 'password')
    # ### end Alembic commands ###
