"""add status to score table

Revision ID: 800f6cacf46e
Revises: 1b25a9a463f9
Create Date: 2025-08-02 22:42:28.734307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800f6cacf46e'
down_revision: Union[str, Sequence[str], None] = '1b25a9a463f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'status')
    # ### end Alembic commands ###
