"""update table classes

Revision ID: 92ef87aaedd0
Revises: 1333609b7436
Create Date: 2026-04-04 11:16:59.459969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ef87aaedd0'
down_revision: Union[str, Sequence[str], None] = '1333609b7436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('registration_open_at', sa.DateTime(), nullable=True))
    op.add_column('classes', sa.Column('registration_close_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'registration_close_at')
    op.drop_column('classes', 'registration_open_at')
    # ### end Alembic commands ###
