"""update database for tuition fees

Revision ID: 9a8e8a76781a
Revises: 4f20cb42d171
Create Date: 2026-04-18 16:04:07.725987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8e8a76781a'
down_revision: Union[str, Sequence[str], None] = '4f20cb42d171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_tuition_fees',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('tuition_fee_id', sa.Uuid(), nullable=False),
    sa.Column('reduction', sa.Float(), nullable=True),
    sa.Column('payable_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('debt_amount', sa.Float(), nullable=True),
    sa.Column('surplus', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tuition_fee_id'], ['tuition_fees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('tuition_fees_student_id_fkey'), 'tuition_fees', type_='foreignkey')
    op.drop_column('tuition_fees', 'surplus')
    op.drop_column('tuition_fees', 'reduction')
    op.drop_column('tuition_fees', 'payable_amount')
    op.drop_column('tuition_fees', 'student_id')
    op.drop_column('tuition_fees', 'paid_amount')
    op.drop_column('tuition_fees', 'debt_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_fees', sa.Column('debt_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tuition_fees', sa.Column('paid_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tuition_fees', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tuition_fees', sa.Column('payable_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('tuition_fees', sa.Column('reduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tuition_fees', sa.Column('surplus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tuition_fees_student_id_fkey'), 'tuition_fees', 'students', ['student_id'], ['id'])
    op.drop_table('student_tuition_fees')
    # ### end Alembic commands ###
