"""update database for management scores

Revision ID: 9b261a17de7f
Revises: 50f1b1d7b91d
Create Date: 2026-03-21 17:21:04.055565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b261a17de7f'
down_revision: Union[str, Sequence[str], None] = '50f1b1d7b91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('score_components_subject_id_fkey'), 'score_components', type_='foreignkey')
    op.drop_column('score_components', 'subject_id')
    op.drop_column('score_components', 'status')
    op.add_column('scores', sa.Column('subject_id', sa.Uuid(), nullable=False))
    op.add_column('scores', sa.Column('academic_term_id', sa.Uuid(), nullable=False))
    op.alter_column('scores', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'scores', 'academic_terms', ['academic_term_id'], ['id'])
    op.create_foreign_key(None, 'scores', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.alter_column('scores', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('scores', 'academic_term_id')
    op.drop_column('scores', 'subject_id')
    op.add_column('score_components', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('score_components', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('score_components_subject_id_fkey'), 'score_components', 'subjects', ['subject_id'], ['id'])
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
