"""update user information

Revision ID: a6989b21a080
Revises: ef7265c83fd7
Create Date: 2025-08-16 21:27:54.705612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6989b21a080'
down_revision: Union[str, Sequence[str], None] = 'ef7265c83fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_informations', sa.Column('place_of_origin', sa.Text(), nullable=True))
    op.add_column('user_informations', sa.Column('exempted_group', sa.Text(), nullable=True))
    op.add_column('user_informations', sa.Column('priority_group', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_informations', 'priority_group')
    op.drop_column('user_informations', 'exempted_group')
    op.drop_column('user_informations', 'place_of_origin')
    # ### end Alembic commands ###
