"""update database to monolith

Revision ID: ab35ce3b0491
Revises: 247757407185
Create Date: 2026-03-07 14:38:48.391458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab35ce3b0491'
down_revision: Union[str, Sequence[str], None] = '247757407185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_class_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('teachers_department_id_fkey'), 'teachers', type_='foreignkey')
    op.alter_column('user_informations', 'citizen_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_informations', 'citizen_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.create_foreign_key(op.f('teachers_department_id_fkey'), 'teachers', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('students_class_id_fkey'), 'students', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###
