"""add bank info to user_informations

Revision ID: be8dd00bed85
Revises: 1f53d9c70b0e
Create Date: 2025-07-20 13:45:19.771294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be8dd00bed85'
down_revision: Union[str, Sequence[str], None] = '1f53d9c70b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_informations', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('user_informations', sa.Column('bank_account_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_informations', 'bank_account_number')
    op.drop_column('user_informations', 'bank_name')
    # ### end Alembic commands ###
