"""remove unique on user information

Revision ID: c2594547d346
Revises: ab35ce3b0491
Create Date: 2026-03-07 14:56:07.148614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2594547d346'
down_revision: Union[str, Sequence[str], None] = 'ab35ce3b0491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_informations_citizen_id_key'), 'user_informations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_informations_citizen_id_key'), 'user_informations', ['citizen_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
