"""add column term to training program subject

Revision ID: c28b9a4850ca
Revises: 7564070f97b2
Create Date: 2026-03-29 20:53:57.005759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28b9a4850ca'
down_revision: Union[str, Sequence[str], None] = '7564070f97b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_program_subject', sa.Column('term', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_program_subject', 'term')
    # ### end Alembic commands ###
