"""delete_FK_Student_and_Teacher

Revision ID: d8b5bce6a815
Revises: db9453538114
Create Date: 2025-10-25 22:38:59.442540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b5bce6a815'
down_revision: Union[str, Sequence[str], None] = 'db9453538114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('classes_teacher_id_fkey'), 'classes', type_='foreignkey')
    op.drop_constraint(op.f('examination_schedules_invigilator_2_id_fkey'), 'examination_schedules', type_='foreignkey')
    op.drop_constraint(op.f('examination_schedules_invigilator_1_id_fkey'), 'examination_schedules', type_='foreignkey')
    op.alter_column('scores', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('scores_student_id_fkey'), 'scores', type_='foreignkey')
    op.alter_column('teaching_schedules', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('teaching_schedules_teacher_id_fkey'), 'teaching_schedules', type_='foreignkey')
    op.alter_column('tuition_fees', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('tuition_fees_student_id_fkey'), 'tuition_fees', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('tuition_fees_student_id_fkey'), 'tuition_fees', 'students', ['student_id'], ['id'])
    op.alter_column('tuition_fees', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(op.f('teaching_schedules_teacher_id_fkey'), 'teaching_schedules', 'teachers', ['teacher_id'], ['id'])
    op.alter_column('teaching_schedules', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(op.f('scores_student_id_fkey'), 'scores', 'students', ['student_id'], ['id'])
    op.alter_column('scores', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(op.f('examination_schedules_invigilator_1_id_fkey'), 'examination_schedules', 'teachers', ['invigilator_1_id'], ['id'])
    op.create_foreign_key(op.f('examination_schedules_invigilator_2_id_fkey'), 'examination_schedules', 'teachers', ['invigilator_2_id'], ['id'])
    op.create_foreign_key(op.f('classes_teacher_id_fkey'), 'classes', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
