"""update subject and class schemas

Revision ID: db9453538114
Revises: a6989b21a080
Create Date: 2025-10-25 16:29:35.998762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9453538114'
down_revision: Union[str, Sequence[str], None] = 'a6989b21a080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('class_name', sa.String(length=100), nullable=True))
    op.add_column('subjects', sa.Column('subject_code', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'subject_code')
    op.drop_column('classes', 'class_name')
    # ### end Alembic commands ###
