"""update score component table

Revision ID: ef7265c83fd7
Revises: 5b5ebd630176
Create Date: 2025-08-03 01:31:50.944863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7265c83fd7'
down_revision: Union[str, Sequence[str], None] = '5b5ebd630176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_components', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_components', 'status')
    # ### end Alembic commands ###
