"""add status to student_tuition_fees

Revision ID: f7eceda2fb56
Revises: be241020172d
Create Date: 2026-05-25 22:55:12.027733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7eceda2fb56'
down_revision: Union[str, Sequence[str], None] = 'be241020172d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'score_component_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('student_tuition_fees', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_tuition_fees', 'status')
    op.alter_column('scores', 'score_component_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
